/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

// Bindings in `worker-configuration.d.ts` are generated by `npm run cf-typegen`.
// Secrets are not part of the Wrangler config, so declare them here.
// `env` from 'cloudflare:workers' is typed as `Cloudflare.Env`.
declare namespace Cloudflare {
  interface Env {
    /** Secret used to salt IP hashes. Set with `wrangler secret put IP_SALT`. */
    IP_SALT?: string;
  }
}
